
package rs.ac.uns.ftn.banka;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import rs.ac.uns.ftn.nalog.Nalog;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NalogZaUplatu", targetNamespace = "http://ftn.uns.ac.rs/banka")
@XmlSeeAlso({
    rs.ac.uns.ftn.banka.ObjectFactory.class,
    rs.ac.uns.ftn.nalog.ObjectFactory.class
})
public interface NalogZaUplatu {


    /**
     * 
     * @param nalog
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obradiNalog", targetNamespace = "http://ftn.uns.ac.rs/nalog", className = "rs.ac.uns.ftn.nalog.ObradiNalog")
    @ResponseWrapper(localName = "obradiNalogResponse", targetNamespace = "http://ftn.uns.ac.rs/banka", className = "rs.ac.uns.ftn.banka.ObradiNalogResponse")
    @Action(input = "http://ftn.uns.ac.rs/banka/NalogZaUplatu/obradiNalogRequest", output = "http://ftn.uns.ac.rs/banka/NalogZaUplatu/obradiNalogResponse")
    public String obradiNalog(
        @WebParam(name = "nalog", targetNamespace = "http://ftn.uns.ac.rs/nalog")
        Nalog nalog);

}
