
package rs.ac.uns.ftn.banka;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NalogZaUplatuService", targetNamespace = "http://ftn.uns.ac.rs/banka", wsdlLocation = "http://NINA:8085/Banka/NalogZaUplatuService?wsdl")
public class NalogZaUplatuService
    extends Service
{

    private final static URL NALOGZAUPLATUSERVICE_WSDL_LOCATION;
    private final static WebServiceException NALOGZAUPLATUSERVICE_EXCEPTION;
    private final static QName NALOGZAUPLATUSERVICE_QNAME = new QName("http://ftn.uns.ac.rs/banka", "NalogZaUplatuService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://NINA:8085/Banka/NalogZaUplatuService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NALOGZAUPLATUSERVICE_WSDL_LOCATION = url;
        NALOGZAUPLATUSERVICE_EXCEPTION = e;
    }

    public NalogZaUplatuService() {
        super(__getWsdlLocation(), NALOGZAUPLATUSERVICE_QNAME);
    }

    public NalogZaUplatuService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NALOGZAUPLATUSERVICE_QNAME, features);
    }

    public NalogZaUplatuService(URL wsdlLocation) {
        super(wsdlLocation, NALOGZAUPLATUSERVICE_QNAME);
    }

    public NalogZaUplatuService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NALOGZAUPLATUSERVICE_QNAME, features);
    }

    public NalogZaUplatuService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NalogZaUplatuService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NalogZaUplatu
     */
    @WebEndpoint(name = "NalogZaUplatu")
    public NalogZaUplatu getNalogZaUplatu() {
        return super.getPort(new QName("http://ftn.uns.ac.rs/banka", "NalogZaUplatu"), NalogZaUplatu.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NalogZaUplatu
     */
    @WebEndpoint(name = "NalogZaUplatu")
    public NalogZaUplatu getNalogZaUplatu(WebServiceFeature... features) {
        return super.getPort(new QName("http://ftn.uns.ac.rs/banka", "NalogZaUplatu"), NalogZaUplatu.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NALOGZAUPLATUSERVICE_EXCEPTION!= null) {
            throw NALOGZAUPLATUSERVICE_EXCEPTION;
        }
        return NALOGZAUPLATUSERVICE_WSDL_LOCATION;
    }

}
