//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.24 at 02:40:47 AM CEST 
//


package faktura;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for faktura complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="faktura">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://ftn.uns.ac.rs/faktura}zaglavljeFakture"/>
 *         &lt;element ref="{http://ftn.uns.ac.rs/faktura}stavkaFakture" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "faktura", propOrder = {
    "zaglavljeFakture",
    "stavkaFakture"
})
public class Faktura {

    @XmlElement(required = true)
    protected ZaglavljeFakture zaglavljeFakture;
    @XmlElement(required = true)
    protected List<StavkaFakture> stavkaFakture;

    /**
     * Gets the value of the zaglavljeFakture property.
     * 
     * @return
     *     possible object is
     *     {@link ZaglavljeFakture }
     *     
     */
    public ZaglavljeFakture getZaglavljeFakture() {
        return zaglavljeFakture;
    }

    /**
     * Sets the value of the zaglavljeFakture property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZaglavljeFakture }
     *     
     */
    public void setZaglavljeFakture(ZaglavljeFakture value) {
        this.zaglavljeFakture = value;
    }

    /**
     * Gets the value of the stavkaFakture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavkaFakture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavkaFakture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StavkaFakture }
     * 
     * 
     */
    public List<StavkaFakture> getStavkaFakture() {
        if (stavkaFakture == null) {
            stavkaFakture = new ArrayList<StavkaFakture>();
        }
        return this.stavkaFakture;
    }

	public void setStavkaFakture(List<StavkaFakture> stavkaFakture) {
		this.stavkaFakture=stavkaFakture;
	}
    
    
    public Faktura() {
		super();
	}
    
    

}
