//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.07.22 at 03:21:51 PM CEST 
//


package faktura;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for zaglavljeFakture complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="zaglavljeFakture">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPoruke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="nazivDobavljac" type="{http://ftn.uns.ac.rs/tipovi}tipString255"/>
 *         &lt;element name="adresaDobavljac" type="{http://ftn.uns.ac.rs/tipovi}tipString255"/>
 *         &lt;element name="pibDobavljac" type="{http://ftn.uns.ac.rs/tipovi}tipPIB"/>
 *         &lt;element name="nazivKupac">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="55"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="adresaKupac">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="55"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="pibKupac" type="{http://ftn.uns.ac.rs/tipovi}tipPIB"/>
 *         &lt;element name="brojRacuna">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;totalDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datumRacuna" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="vrednostRobe" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="vrednostUsluga" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="ukupnoRobaIUsluge" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="ukupanRabat" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="ukupanPorez" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="valuta">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="iznosZaUplatu" type="{http://ftn.uns.ac.rs/tipovi}tipDec15_2"/>
 *         &lt;element name="uplataNaRacun" type="{http://ftn.uns.ac.rs/tipovi}tipRacun"/>
 *         &lt;element name="datumValute" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "zaglavljeFakture", propOrder = {
    "idPoruke",
    "nazivDobavljac",
    "adresaDobavljac",
    "pibDobavljac",
    "nazivKupac",
    "adresaKupac",
    "pibKupac",
    "brojRacuna",
    "datumRacuna",
    "vrednostRobe",
    "vrednostUsluga",
    "ukupnoRobaIUsluge",
    "ukupanRabat",
    "ukupanPorez",
    "valuta",
    "iznosZaUplatu",
    "uplataNaRacun",
    "datumValute"
})
public class ZaglavljeFakture {

    @XmlElement(required = true)
    protected String idPoruke;
    @XmlElement(required = true)
    protected String nazivDobavljac;
    @XmlElement(required = true)
    protected String adresaDobavljac;
    @XmlElement(required = true)
    protected String pibDobavljac;
    @XmlElement(required = true)
    protected String nazivKupac;
    @XmlElement(required = true)
    protected String adresaKupac;
    @XmlElement(required = true)
    protected String pibKupac;
    @XmlElement(required = true)
    protected BigDecimal brojRacuna;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumRacuna;
    @XmlElement(required = true)
    protected BigDecimal vrednostRobe;
    @XmlElement(required = true)
    protected BigDecimal vrednostUsluga;
    @XmlElement(required = true)
    protected BigDecimal ukupnoRobaIUsluge;
    @XmlElement(required = true)
    protected BigDecimal ukupanRabat;
    @XmlElement(required = true)
    protected BigDecimal ukupanPorez;
    @XmlElement(required = true)
    protected String valuta;
    @XmlElement(required = true)
    protected BigDecimal iznosZaUplatu;
    @XmlElement(required = true)
    protected String uplataNaRacun;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumValute;

    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPoruke(String value) {
        this.idPoruke = value;
    }

    /**
     * Gets the value of the nazivDobavljac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivDobavljac() {
        return nazivDobavljac;
    }

    /**
     * Sets the value of the nazivDobavljac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivDobavljac(String value) {
        this.nazivDobavljac = value;
    }

    /**
     * Gets the value of the adresaDobavljac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaDobavljac() {
        return adresaDobavljac;
    }

    /**
     * Sets the value of the adresaDobavljac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaDobavljac(String value) {
        this.adresaDobavljac = value;
    }

    /**
     * Gets the value of the pibDobavljac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPibDobavljac() {
        return pibDobavljac;
    }

    /**
     * Sets the value of the pibDobavljac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPibDobavljac(String value) {
        this.pibDobavljac = value;
    }

    /**
     * Gets the value of the nazivKupac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivKupac() {
        return nazivKupac;
    }

    /**
     * Sets the value of the nazivKupac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivKupac(String value) {
        this.nazivKupac = value;
    }

    /**
     * Gets the value of the adresaKupac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdresaKupac() {
        return adresaKupac;
    }

    /**
     * Sets the value of the adresaKupac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdresaKupac(String value) {
        this.adresaKupac = value;
    }

    /**
     * Gets the value of the pibKupac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPibKupac() {
        return pibKupac;
    }

    /**
     * Sets the value of the pibKupac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPibKupac(String value) {
        this.pibKupac = value;
    }

    /**
     * Gets the value of the brojRacuna property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getBrojRacuna() {
        return brojRacuna;
    }

    /**
     * Sets the value of the brojRacuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setBrojRacuna(BigDecimal value) {
        this.brojRacuna = value;
    }

    /**
     * Gets the value of the datumRacuna property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumRacuna() {
        return datumRacuna;
    }

    /**
     * Sets the value of the datumRacuna property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumRacuna(XMLGregorianCalendar value) {
        this.datumRacuna = value;
    }

    /**
     * Gets the value of the vrednostRobe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostRobe() {
        return vrednostRobe;
    }

    /**
     * Sets the value of the vrednostRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostRobe(BigDecimal value) {
        this.vrednostRobe = value;
    }

    /**
     * Gets the value of the vrednostUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostUsluga() {
        return vrednostUsluga;
    }

    /**
     * Sets the value of the vrednostUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostUsluga(BigDecimal value) {
        this.vrednostUsluga = value;
    }

    /**
     * Gets the value of the ukupnoRobaIUsluge property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupnoRobaIUsluge() {
        return ukupnoRobaIUsluge;
    }

    /**
     * Sets the value of the ukupnoRobaIUsluge property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupnoRobaIUsluge(BigDecimal value) {
        this.ukupnoRobaIUsluge = value;
    }

    /**
     * Gets the value of the ukupanRabat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanRabat() {
        return ukupanRabat;
    }

    /**
     * Sets the value of the ukupanRabat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanRabat(BigDecimal value) {
        this.ukupanRabat = value;
    }

    /**
     * Gets the value of the ukupanPorez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanPorez() {
        return ukupanPorez;
    }

    /**
     * Sets the value of the ukupanPorez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanPorez(BigDecimal value) {
        this.ukupanPorez = value;
    }

    /**
     * Gets the value of the valuta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValuta() {
        return valuta;
    }

    /**
     * Sets the value of the valuta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValuta(String value) {
        this.valuta = value;
    }

    /**
     * Gets the value of the iznosZaUplatu property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznosZaUplatu() {
        return iznosZaUplatu;
    }

    /**
     * Sets the value of the iznosZaUplatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznosZaUplatu(BigDecimal value) {
        this.iznosZaUplatu = value;
    }

    /**
     * Gets the value of the uplataNaRacun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUplataNaRacun() {
        return uplataNaRacun;
    }

    /**
     * Sets the value of the uplataNaRacun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUplataNaRacun(String value) {
        this.uplataNaRacun = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumValute() {
        return datumValute;
    }

    /**
     * Sets the value of the datumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumValute(XMLGregorianCalendar value) {
        this.datumValute = value;
    }

}
